name: deepcrunch-ci-environment
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.1.2
  
  # linting and formatting
  - black=23.3.0
  - flake8=6.1.0
  - autopep8=2.0.2
  - isort=5.12.0
  - clang-format=16.0.6
  - nbstripout
  
  # build tools
  - make
  - setuptools=68.0.0
  
  # testing dependencies
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - pytest-timeout=2.1.0
  - pytest-xdist=3.3.1
  
  # runtime dependencies for tests
  - numpy=1.24.3
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cpuonly
  - onnx=1.14.0
  
  # pip packages
  - pip:
    - onnxruntime==1.15.1
    - neural-compressor==2.3.1
